name: Automated Release
on:
  push:
    branches:
      - "main"
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.0.1 [CE|EE|ECE 2.4.0-2.4.7] 28 May 2024
          tag_name: 1.0.1
          body: |-
            - **Enhancement**: Added category `description` and `gc_metadata` attributes to the sample data setup.
            - **Enhancement**: Added `media gallery assets` to the sample data setup.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
