name: Automated Release
on:
  push:
    branches:
      - "main"
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.0.2 [CE|EE|ECE 2.4.0-2.4.7] 29 May 2024
          tag_name: 1.0.2
          body: |-
            - **Fix**: Apply a fix to CMS page installer where store ID should be retrieved directly from DB during sample data installation process. [#1]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
