name: Automated Release
on:
  push:
    branches:
      - "main"
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.0.5 [CE|EE|ECE 2.4.0-2.4.7] 01 Jun 2024
          tag_name: 1.0.5
          body: |-
            - **Fix**: Apply a fix to category `description` and `gc_metadata` attribute data setup.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
